### ISSUE TITLE
Tracking: enable EVE services to run as a series of containers not in a device

### ISSUE THREAD

**Issue by deitch** [lf-edge/eve#734]
This is a tracking issue.

EVE currently runs as a series of services in containers - mostly a few and one big one called `pillar` - on a device.

We have two goals:

1. Extract all of the services from inside a device (real or virtual), so we can run them as a set of containers on any linux host. For example, use docker compose to run them all directly on a laptop or an AWS VM, _not_ inside a physical device or qemu virtual device.
2. Enable each service to run standalone without any other services. For example, run `downloader` all by itself.

This is the tracking issue for the first. It is a place for design discussions as well as the checklist for what is needed. Each item on the checklist should have a PR link next to it.

- [ ] create compose file
- [ ] create run target in Makefile
- [ ] update watchdog so it doesn't try to reboot when running in compose
- [ ] more points here @rvs
